### ISSUE TITLE
Glavni kostur pograma

### ISSUE THREAD

**Issue by VuceticBranislav** [HECalculator/HECalculator#5]
- [x] Glavni kostur pograma
Treba da sadrzi primenu funkcija za unos, racunanje i prikaz.
Ovo je main funkcija koja po potrebi poziva ostale.
Software interface i report treba da su na Engleskom.

**Comment by ivantot** [comment]
Mozda jedna od napomena da bude da je program na engleskom!
Ne znam da li je ovo pravo mesto za takvu napomenu.

**Comment by VuceticBranislav** [comment]
Aha, dodao sam ovde i na wiki.
