### ISSUE TITLE
Funkcije za unos inputa za proracun

### ISSUE THREAD

**Issue by VuceticBranislav** [HECalculator/HECalculator#6]
- [x] Funkcije za unos inputa za proracun
Potrebne funkcije za dobavljanje polaznih podataka od korisnika. Ovde spadaju svi polazni podatci kao sto su:
- Geometrija lifting luga
- Opterecenje na lugu
- Materijal luga

**Comment by ivantot** [comment]
Htedoh da ostane trag o ovoj diskusiji.. nisam siguran oko sledeceg. Naime, mozemo ici na varijantu da sve promenljive koje unosi user i koje sluze za racunanje budu member promenljive (za njih je automatska inicijalizacija). Bile bi vidljive kroz celu klasu (mada nama treba da su vidljive samo u mainu) a potprogrami ne bi morali da ih ucitavaju kao parametre nego bi radili sa njima direktno ih citajuci i menjajuci po potrebi. Koliko razumem, cena je memorija :).
Drugi nacin je da deklarisemo (i inicijalizujemo) promenljive u mainu, tada bi bile lokalne. Potprogrami koji se pozivaju u mainu bi morali parametarski prihvatati promenljive i raditi sa njima.
Kakva su misljenja?

**Comment by VuceticBranislav** [comment]
Mozemo membere da koristimo. Slicno cemo raditi kad predemo na OOP. Lakse je de pristupis iz klase i nemoras da saljes kroz parametre.
