### ISSUE TITLE
Funkcije za racunanje

### ISSUE THREAD

**Issue by VuceticBranislav** [HECalculator/HECalculator#7]
- [x] Funkcije za racunanje
Ovde bi bilo potrebno uraditi racunicu i pripremiti sve podatke potrebne za report:
- Vrednosti na osnovu kojih ce se doneti azkljucak o adekvatnosti lifting luga - zakljucak

**Comment by ivantot** [comment]
Pogledaj na primeru koji imamo racunicu za allowable bearing stress.. kaze min (0.75*YIELD, 0.9*YIELD). Fali nam jedan YIELD (pad ili shell)?
Takodje, u racunici sa wikija ima problem u zaokruzivanju ;).

**Comment by VuceticBranislav** [comment]
Popravljene slike na wiki. Popravio sam yield na 244MPa.
Iz nekog razloga podatak u input echo i u proracunu nije isti. Verovatno je nesto prekucavana u proracunu pa nije popravljenu svuda gde treba.
Obrisao sam visak formule kod allowable bearing stressa. Originalna formula uzima u obzir jos jedan faktor koji je obrisan i stoji uz 0.75. Neka za sad bude allowable stress = 0.75 yield.

**Comment by ivantot** [comment]
Valja :)

**Comment by ivantot** [comment]
E fali nam i input za occfac koji se koristi u racunici za allowable lug stress.

**Comment by VuceticBranislav** [comment]
Evo popravio sam ga. Izbacio sam taj occfac. To je bio problem i prosli put. Sad ga vise nema.
U sustini on je uvek 1 i nismo ga nikad menjali pa je bolje da nemamo ni njega ni input za njega :D.

**Comment by ivantot** [comment]
![image](https://user-images.githubusercontent.com/69508160/107470155-3a606280-6b6b-11eb-9292-32bc8e12fa1e.png)

**Comment by ivantot** [comment]
vidi ti to, radi kazenje slika u komentar :D

**Comment by ivantot** [comment]
kako je ovo 600? :)

**Comment by VuceticBranislav** [comment]
hahah pa kolko gresaka moze da bude u ovom proracunu.
Treba da bude sila / povrsinu. To da bi bila povrsinam ora da bude pomnozeno sa debljinom luga.
Treba da stoji ... / (2*(r-dh/2)*t.
Popravio sam na wiki.
